# Generated by Django 3.0.3 on 2020-02-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('max_size', models.FloatField()),
                ('water_type', models.CharField(max_length=50)),
            ],
        ),
    ]
