# Generated by Django 3.0.3 on 2020-03-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciesprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='species-images'),
        ),
    ]
