# Generated by Django 3.0.3 on 2020-06-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciesprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
