# Generated by Django 3.0.3 on 2020-06-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speciesprofile', '0002_auto_20200622_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='water_type',
            field=models.CharField(choices=[('Fresh', 'Freshwater'), ('Salt', 'Saltwater'), ('Brackish', 'Brackish water')], max_length=10),
        ),
    ]
