# Generated by Django 3.0.3 on 2020-03-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speciesprofile', '0002_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='species-images')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speciesprofile.Profile')),
            ],
        ),
    ]
